version: '3.7'

services:
  apache:
    build:
      context: ./docker/apache
      dockerfile: Dockerfile
    cap_add:
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    networks:
      - private
    ports:
      - "80:8088"

  php-fpm:
    build:
      context: ./docker/fpm
      dockerfile: Dockerfile
    cap_drop:
      - ALL
    networks:
      private:
        aliases:
         - phpfpm
    ports:
      - "9000:9000"

networks:
  private:
    driver: bridge
